### ISSUE TITLE
Error when trying to use ExNavigation

### ISSUE THREAD

**Issue by oren** [exponentjs/exponent#12]
First time using react and exponent. Let me know if there is a better place to ask this question.

I would like to have a basic routing so I believe ex-navigation is the recommended way to do it. please correct me if I am wrong. I heard about it in one of the introduction videos.

I copy pasted the example from https://github.com/exponentjs/ex-navigation. The only modification I made is changed `AppRegistry.registerComponent` to `Exponent.registerComponent`. From some reason I get this error: "SyntaxError: /home/oren/p/exponent/login/node_modules/@exponent/ex-navigation/src/ExNavigation.js: Unexpected token (32:9)"

This is the offending line: `export * as NavigationStyles from './ExNavigationStyles';`

Here is my code: https://github.com/oren/login/blob/69588f799b7706410b55f9a638cc09810de50e72/main.js

Thanks!

**Comment by ide** [comment]
`export *` is JS syntax that RN doesn't support out of the box. You'll need to configure Babel. Make a .babelrc like this: https://github.com/exponentjs/ex-navigation/blob/master/example/.babelrc and add `babel-preset-react-native-stage-0` (and optionally `babel-plugin-transform-react-jsx-source`) to your `devDependencies` and try again.

**Comment by oren** [comment]
Thanks.
now I am getting: `undefined is not a function (evaluating '_exponent2.default.registerComponent('main', function() {return App;})')`.

Interesting fact - i don't see that error in the exponent window. it's only showing on my phone.

**Comment by satya164** [comment]
@oren it's `Exponent.registerRootComponent(App)` not `Exponent.registerComponent('main', () => App)`

**Comment by oren** [comment]
works now. thanks!
