### ISSUE TITLE
Usage with react-native-navigation

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [exponentjs/exponent#13]
Hello! I started using exponent today and now i'm trying to use https://github.com/wix/react-native-navigation in my exponent's project

The problem is that react-native-navigation requires you to start the root of your app in a different way:
**index.ios.js**
```js
import { Navigation } from 'react-native-navigation';

import { registerScreens } from './screens';
registerScreens(); // this is where you register all of your app's screens

// start the app
Navigation.startTabBasedApp({
  tabs: [
    {
      label: 'One',
      screen: 'example.FirstTabScreen', // this is a registered name for a screen
      icon: require('../img/one.png'),
      selectedIcon: require('../img/one_selected.png'),
      title: 'Screen One'
    },
    {
      label: 'Two',
      screen: 'example.SecondTabScreen',
      icon: require('../img/two.png'),
      selectedIcon: require('../img/two_selected.png'),
      title: 'Screen Two'
    }
  ]
});
```

And I noticed that exponent requires you to start your app with this special function:
```Exponent.registerRootComponent(App);```

That probably does a lot more than the normal one

Is it possible to use these two technologies together?

**Comment by brentvatne** [comment]
Hi there!

We do not support react-native-navigation -- it has custom native dependencies. We suggest ex-navigation instead -- https://github.com/exponentjs/ex-navigation

See:
- https://docs.getexponent.com/versions/v11.0.0/introduction/faq.html#how-do-i-add-custom-native-code-to-my-exponent-project
- https://blog.getexponent.com/answered-on-slack-ejecting-from-exponent-154bdca57dc1#.laubbnos4

**Comment by rangerscience** [comment]
This seems like it should be resolvable if people from both projects can put their heads together - Expo requires an App object to be supplied, and presumable, at some point React-Native-Navigation produces that object. Just need to expose things at the proper point in the pipeline...?

**Comment by feldrok** [comment]
Please, we would love support of react-native-navigation, looks so smooth and easy to use compared to other solutions...

**Comment by javidjamae** [comment]
React Navigation has a lot of issues. It would be great to have an alternative choice in Expo with React Native Navigation.

**Comment by sebasibarguen** [comment]
Is there any plans for supporting react-native-nagivation?

**Comment by camdagr8** [comment]
Would love to have this.

**Comment by anp** [comment]
Hi everyone! Please use the [feature request](https://expo.canny.io) board to vote for feature requests so we can look at everything in one place when evaluating what to work on. Thanks!
