### ISSUE TITLE
Link native libraries

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [exponentjs/exponent#14]
Hello
I'm trying to use this library:
https://github.com/xinthink/react-native-material-kit

It requires to set up some native dependencies:
```
JDK 7+ is required
Add the following snippet to your android/settings.gradle:

include ':RNMaterialKit'
project(':RNMaterialKit').projectDir = file('../node_modules/react-native-material-kit/android')
Declare the dependency in your android/app/build.gradle

dependencies {
    ...
    compile project(':RNMaterialKit')
}
Import com.github.xinthink.rnmk.ReactMaterialKitPackage and register it in your MainActivity (or equivalent, RN >= 0.32 MainApplication.java):

@Override
protected List<ReactPackage> getPackages() {
    return Arrays.asList(
            new MainReactPackage(),
            new ReactMaterialKitPackage()
    );
}
```

How can I do this in a exponent project?

**Comment by aliklev** [comment]
Answer in the FAQ:
How do I add custom native code to my Exponent project?
[https://docs.getexponent.com/versions/v11.0.0/introduction/faq.html](url)

**Comment by brentvatne** [comment]
We should try to move UI libraries like this away from native dependencies so they can be easily supported with Exponent. Native modules have two use cases right now:
1) Expose an API that is not currently available to JS
2) Do something that you can do in JS but more performantly

UI libraries will only include native code that falls under category 2, so the answer is to improve react-native such that it is not necessary to drop down to native code. This means improving animations to allow them to run on the main thread (coming along nicely!), improving the gesture system, etc.

In this particular case, I believe custom native code is used for the loading spinner effect. Once we add support for `Animated.loop` and make it possible to run looped animations on the main thread there will be no need for custom native code for this.

**Comment by alexprice91** [comment]
@brentvatne what about use case 1? This is a deal breaker for me

**Comment by brentvatne** [comment]
https://docs.expo.io/versions/latest/guides/detach.html :)
