### ISSUE TITLE
QR code support

### ISSUE THREAD

**Issue by brentvatne** [exponentjs/exponent#2]
Needed by @patcito and @simzen85, amongst others

We might:
- Import react-native-camera directly and put it under `Exponent.Components.Experimental.Camera`
- Make QR capture a mode for ImagePicker

**Comment by jsierles** [comment]
Would be useful for rnplay.org as well, so people can load apps on the device without having to login sign up.

**Comment by simzen85** [comment]
Do we have any estimate timeline for this ? Thanks

**Comment by brentvatne** [comment]
I am working on this for SDK11, eta ~3-4 weeks

**Comment by brentvatne** [comment]
took longer than expected, sorry, sdk11 is being submitted tomorrow

**Comment by brentvatne** [comment]
done in sdk11! https://docs.getexponent.com/versions/v11.0.0/sdk/bar-code-scanner.html
