### ISSUE TITLE
What's the story with iPad support?

### ISSUE THREAD

**Issue by bolinfest** [exponentjs/exponent#4]
I can load the exponent app on my iPad, but it appears to be in iPhone emulation mode on the small screen.

**Comment by brentvatne** [comment]
cc @terribleben

**Comment by terribleben** [comment]
Hi @bolinfest, as you've observed, we don't currently target iPad in the exponent iOS client. I can add it to our roadmap for one of the next SDKs if it's important to you.

**Comment by neonsquare** [comment]
+1 from me - iPad support would be important

**Comment by chownation** [comment]
+1

On Sun, Oct 16, 2016 at 6:21 AM, Jochen H. Schmidt <notifications@github.com

**Comment by jacklam718** [comment]
+1 - I want iPad support too.

**Comment by andrejunges** [comment]
+1 😄

**Comment by cameronbarker** [comment]
+1

**Comment by xcarpentier** [comment]
+1

**Comment by terribleben** [comment]
We're supporting this in SDK 11, which we're planning to release sometime this week.

**Comment by terribleben** [comment]
Supported in SDK 11! https://blog.getexponent.com/exponent-sdk-v11-0-0-is-now-available-6c1c93abc5ae

**Comment by chownation** [comment]
Nice work! 👍🏼
Saw that iPad resolution works in the latest release of Exponent client app in App Store. 






On Mon, Nov 7, 2016 at 7:35 PM -0500, "Ben Roth" <notifications@github.com> wrote:












Supported in SDK 11! https://blog.getexponent.com/exponent-sdk-v11-0-0-is-now-available-6c1c93abc5ae
