### ISSUE TITLE
IOS build - Code Sign error: No code signing identities found: 

### ISSUE THREAD

**Issue by tiensonqin** [exponentjs/exponent#5]
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “C8D8QTF339” were found.

**Comment by brentvatne** [comment]
@tiensonqin - were you able to resolve this?

**Comment by tiensonqin** [comment]
I have no problem with master branch, you can close this issue.
On Mon, 31 Oct 2016, 00:13 Brent Vatne, <notifications@github.com> wrote:

@tiensonqin <https://github.com/tiensonqin> - were you able to resolve this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/exponentjs/exponent/issues/5#issuecomment-257160505>,
or mute the thread
