### ISSUE TITLE
Issue with Location permission checking on Android < 6

### ISSUE THREAD

**Issue by simzen85** [exponentjs/exponent#7]
As discussed with @brentvatne , there is a bug where `Permissions.getAsync` for LOCATION always returns "denied" even if the permission is actually granted. 

It seems to also lead to the issue where `Permissions.askAsync` won't fire the dialog so that user can grant/not grant the permission.

**Comment by nikki93** [comment]
Hi! Sorry for taking a while on this issue. We will release a fix for this in our next SDK version (SDK 11) that will come out the week of October 31!

**Comment by brentvatne** [comment]
this should be fixed in sdk11!
