### ISSUE TITLE
Building standalone iOS app

### ISSUE THREAD

**Issue by pyankoff** [exponentjs/exponent#8]
Hi! I'm trying to build a standalone app, but having trouble with `configure` step of the process. Running:
```
gulp ios-shell-app --url MYURL --action configure --type archive --archivePath ../shellAppBase-archive/Exponent.xcarchive --sdkVersion 10.0.0
```
Getting the following error:
```
Modifying config files under /Users/andrey/hack/exapp/shellAppBase-archive/Exponent.xcarchive...
/Users/andrey/hack/exapp/shellAppBase-archive/Exponent.xcarchive/EXShell.plist: file does not exist or is not readable or is not a regular file (Error Domain=NSCocoaErrorDomain Code=260 "The file “EXShell.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/andrey/hack/exapp/shellAppBase-archive/Exponent.xcarchive/EXShell.plist, NSUnderlyingError=0x7fdf57d00c70 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}})
[22:08:07] 'ios-shell-app' errored after 1.76 s
[22:08:07] Error: ENOENT: no such file or directory, open '/Users/andrey/hack/exapp/shellAppBase-archive/Exponent.xcarchive/EXShell.json'
    at Error (native)
```
Same command works when I run in on `shellAppBase-builds/simulator/Release/Exponent.app`, but how to make it work with archive I can submit to App Store?

Thank you!

**Comment by skevy** [comment]
cc @terribleben

**Comment by pyankoff** [comment]
Seems like I figured it out. Made it work by running `configure` on an `Exponent.app` file which is inside `Exponent.xcarchive` file.

**Comment by brentvatne** [comment]
thanks for followup!

**Comment by lyahdav** [comment]
This happened to me today after detaching an Expo project and changing the name of the project in `exp.json`. It seems the path to `EXShell.plist` is determined using the project name in [Detach.js](https://github.com/expo/xdl/blob/9fe454372c9941f93f92fa61d9a87d54428de93a/src/detach/Detach.js#L681). I resolved by changing the project name back, but would be nice if there was better support for renaming a project in `exp.json` after detaching.

**Comment by geek6** [comment]
I got the same trouble just like @lyahdav . It means you can't change the 'name' in exp.json file if you want to detach an expo project.

**Comment by geek6** [comment]
I got the same trouble just like @lyahdav . I also changed the 'name' in exp.json file before detaching an Expo project.

**Comment by zeeshanjan82** [comment]
I am also experiencing same issue as @lyahdav I have a detached Expo app and when I try changing the name of the app in app.json file and then publish I get this error. Is there any fix for this?

**Comment by manoj-makkuboy** [comment]
In the ejected version you can do this.

> ExpoKit: To change the name of your app, edit the "Display Name" field in Xcode and the app_name string in android/app/src/main/res/values/strings.xml.
