### ISSUE TITLE
ios: TextInput with custom font doesn't pass fontSize

### ISSUE THREAD

**Issue by skabbes** [exponentjs/exponent#9]
### Version Info:

Exponent version: 1.9.2.103786
iOS: iPhone 6 Simulator with iOS 9.2, also verified on _real_ iPhone 6 iOS 10.0.2
Android: Nexus 6P, latest android
### Details:

I was experimenting with loading custom fonts with exponent.  Everything works great with `Text` Components.  As soon as I try to use a `TextInput`, it also works, but always prefers the default font size (whatever that is).

I tried the same code on a friend's above android device, and it was able to successfully change the font size.

If I do _not_ use the custom font, (`fontFamily: undefined`) or if I use a a fontFamily that is built-in to iOS (`fontFamily: 'AmericanTypewriter-CondensedBold'`) then the sizes of the fonts do change.

I am a medium-experienced iOS developer, so I am happy to help with this to the best of my abilities, but I am very new to the exponent codebase, and couldn't root cause this myself :(

**Comment by skevy** [comment]
cc @ben

**Comment by nikki93** [comment]
Fixed by https://github.com/exponentjs/exponent/commit/ba6fb151ff1f97d46be4da271758fe273ea10d67.
